### ISSUE TITLE
onError code does not bubble up to react component

### ISSUE THREAD

**Issue by dfoderick** [moneybutton/react-money-button#1]
Steps to reproduce
1. Run example/src/index.js
2. Change 'to' input from 5 to some invalid number (e.g. 0)
3. Clear the clientIdentifier input (this is another error in your example)
4. Slide money button
Expected behavior: error should show in alert popup
Observed: 500 error is showing in browser console and therefore the react onerror never runs.

Additional info:
Error logged in console is
"VM1064 v2.js:1 Uncaught (in promise) e {status: 500, title: "Server Error", detail: "An unexpected error has ocurred. Please, try again in a few minutes.", message: "An unexpected error has ocurred. Please, try again in a few minutes."}"
So its some kind of back end error that is not making its way up to the ui.

**Comment by ryanxcharles** [comment]
This was a problem with the button itself, not the React component. We have fixed the issue. Please let us know if you continue to have issues.

**Comment by dfoderick** [comment]
That works. The parameter that gets passed into the error handler just says "unexpected error".
If someone is getting this error then usually its because they configured the money button incorrectly.
